/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_0.h"
#include "Pin_Red.h"
#include "Pin_Red_aliases.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "Timer.h"
#include "PWM_2_Out.h"
#include "PWM_2_Out_aliases.h"
#include "PWM_1_Out.h"
#include "PWM_1_Out_aliases.h"
#include "PWM_0_Out.h"
#include "PWM_0_Out_aliases.h"
#include "PWM_0_Int.h"
#include "Clock_1MHz.h"
#include "Timer_Int.h"
#include "Timer_Pin.h"
#include "Timer_Pin_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

